//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.WcfServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceReference.IWcfService")]
    public interface IWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetCompaniesJson", ReplyAction="http://tempuri.org/IWcfService/GetCompaniesJsonResponse")]
        string GetCompaniesJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetCompaniesJson", ReplyAction="http://tempuri.org/IWcfService/GetCompaniesJsonResponse")]
        System.Threading.Tasks.Task<string> GetCompaniesJsonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/ValidateCompany", ReplyAction="http://tempuri.org/IWcfService/ValidateCompanyResponse")]
        string ValidateCompany(string companyJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/ValidateCompany", ReplyAction="http://tempuri.org/IWcfService/ValidateCompanyResponse")]
        System.Threading.Tasks.Task<string> ValidateCompanyAsync(string companyJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/SaveCompany", ReplyAction="http://tempuri.org/IWcfService/SaveCompanyResponse")]
        void SaveCompany(string companyJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/SaveCompany", ReplyAction="http://tempuri.org/IWcfService/SaveCompanyResponse")]
        System.Threading.Tasks.Task SaveCompanyAsync(string companyJson);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceChannel : PresentationLayer.WcfServiceReference.IWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceClient : System.ServiceModel.ClientBase<PresentationLayer.WcfServiceReference.IWcfService>, PresentationLayer.WcfServiceReference.IWcfService {
        
        public WcfServiceClient() {
        }
        
        public WcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCompaniesJson() {
            return base.Channel.GetCompaniesJson();
        }
        
        public System.Threading.Tasks.Task<string> GetCompaniesJsonAsync() {
            return base.Channel.GetCompaniesJsonAsync();
        }
        
        public string ValidateCompany(string companyJson) {
            return base.Channel.ValidateCompany(companyJson);
        }
        
        public System.Threading.Tasks.Task<string> ValidateCompanyAsync(string companyJson) {
            return base.Channel.ValidateCompanyAsync(companyJson);
        }
        
        public void SaveCompany(string companyJson) {
            base.Channel.SaveCompany(companyJson);
        }
        
        public System.Threading.Tasks.Task SaveCompanyAsync(string companyJson) {
            return base.Channel.SaveCompanyAsync(companyJson);
        }
    }
}
